/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lhm777.percentagecalculator;

import java.awt.Color;
import java.text.NumberFormat;
import java.text.ParsePosition;
import java.util.ArrayList;
import java.util.Locale;
import java.util.regex.Pattern;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JPanel;


public class PercentageCalculatorGUI extends javax.swing.JFrame {

    /**
     * Creates new form PercentageCalculatorGUI
     */
    public PercentageCalculatorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanelMain = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanelPercentage = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jButtonHamburgerMenu = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonRefresh = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jPanel16 = new javax.swing.JPanel();
        jPanelPercentageIncreaseDecrease = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jButtonHamburgerMenu1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButtonRefresh1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jPanel19 = new javax.swing.JPanel();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jPanel50Is1PercentOfWhatNumber = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jButtonHamburgerMenu2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jButtonRefresh2 = new javax.swing.JButton();
        jPanel27 = new javax.swing.JPanel();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jFormattedTextField9 = new javax.swing.JFormattedTextField();
        jPanel29 = new javax.swing.JPanel();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jPanelWhatPercentOf = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jButtonHamburgerMenu3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButtonRefresh3 = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jFormattedTextField10 = new javax.swing.JFormattedTextField();
        jPanel24 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jFormattedTextField11 = new javax.swing.JFormattedTextField();
        jPanel26 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jFormattedTextField12 = new javax.swing.JFormattedTextField();
        jPanel32 = new javax.swing.JPanel();
        jPanelFractionToPercent = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jButtonHamburgerMenu4 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jButtonRefresh4 = new javax.swing.JButton();
        jPanel34 = new javax.swing.JPanel();
        jFormattedTextField13 = new javax.swing.JFormattedTextField();
        jPanel35 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jFormattedTextField14 = new javax.swing.JFormattedTextField();
        jPanel37 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jFormattedTextField15 = new javax.swing.JFormattedTextField();
        jPanel39 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(328, 432));
        setResizable(false);
        setSize(new java.awt.Dimension(328, 432));

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanelMain.setBackground(new java.awt.Color(34, 40, 44));
        jPanelMain.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(34, 40, 44));
        jPanel3.setPreferredSize(new java.awt.Dimension(361, 30));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Math Calculators");
        jPanel3.add(jLabel1, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        jPanelMain.add(jPanel3, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(34, 40, 44));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("What would you like to calculate?");
        jLabel3.setMaximumSize(new java.awt.Dimension(104, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel4.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanelMain.add(jPanel4, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(44, 52, 58));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PercentageCalculatorGUI.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MouseExited(evt);
            }
        });
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Percentage (what is x% of y)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel5.add(jLabel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanelMain.add(jPanel5, gridBagConstraints);

        jPanel10.setBackground(new java.awt.Color(34, 40, 44));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        jPanelMain.add(jPanel10, gridBagConstraints);

        jPanel6.setBackground(new java.awt.Color(44, 52, 58));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PercentageCalculatorGUI.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MouseExited(evt);
            }
        });
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Percentage increase/decrease");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel6.add(jLabel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanelMain.add(jPanel6, gridBagConstraints);

        jPanel7.setBackground(new java.awt.Color(44, 52, 58));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PercentageCalculatorGUI.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MouseExited(evt);
            }
        });
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Percentage (50 is 1% of what number?)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel7.add(jLabel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanelMain.add(jPanel7, gridBagConstraints);

        jPanel8.setBackground(new java.awt.Color(44, 52, 58));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PercentageCalculatorGUI.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MouseExited(evt);
            }
        });
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Percentage (5 is what percent of 25?)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel8.add(jLabel7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanelMain.add(jPanel8, gridBagConstraints);

        jPanel9.setBackground(new java.awt.Color(44, 52, 58));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PercentageCalculatorGUI.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MouseExited(evt);
            }
        });
        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Fraction to Percentage");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel9.add(jLabel8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanelMain.add(jPanel9, gridBagConstraints);

        jPanel1.add(jPanelMain, "card2");

        jPanelPercentage.setMinimumSize(new java.awt.Dimension(275, 387));
        jPanelPercentage.setPreferredSize(new java.awt.Dimension(361, 395));
        jPanelPercentage.setLayout(new java.awt.GridBagLayout());

        jPanel12.setBackground(new java.awt.Color(34, 40, 44));
        jPanel12.setMinimumSize(new java.awt.Dimension(183, 22));
        jPanel12.setPreferredSize(new java.awt.Dimension(334, 432));
        jPanel12.setLayout(new java.awt.GridBagLayout());

        jButtonHamburgerMenu.setBackground(new java.awt.Color(34, 40, 44));
        jButtonHamburgerMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hamburgerMenuIcon.png"))); // NOI18N
        jButtonHamburgerMenu.setBorder(null);
        jButtonHamburgerMenu.setFocusPainted(false);
        jButtonHamburgerMenu.setPreferredSize(new java.awt.Dimension(40, 30));
        jButtonHamburgerMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hamburgerMenuClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel12.add(jButtonHamburgerMenu, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Percentage (what is x% of y)");
        jLabel9.setPreferredSize(new java.awt.Dimension(361, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 0.5;
        jPanel12.add(jLabel9, gridBagConstraints);

        jButtonRefresh.setBackground(new java.awt.Color(34, 40, 44));
        jButtonRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refreshIcon.png"))); // NOI18N
        jButtonRefresh.setBorder(null);
        jButtonRefresh.setPreferredSize(new java.awt.Dimension(40, 30));
        jButtonRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshButtonClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel12.add(jButtonRefresh, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        jPanelPercentage.add(jPanel12, gridBagConstraints);

        jPanel13.setPreferredSize(new java.awt.Dimension(334, 432));
        jPanel13.setLayout(new java.awt.GridBagLayout());

        jFormattedTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.################"))));
        jFormattedTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFormattedTextField1.setPreferredSize(new java.awt.Dimension(334, 432));
        jFormattedTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PercentageCalculatorGUI.this.focusLost(evt);
            }
        });
        jFormattedTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PercentageCalculatorGUI.this.keyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 37, 0, 0);
        jPanel13.add(jFormattedTextField1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel13.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        jPanelPercentage.add(jPanel13, gridBagConstraints);

        jPanel14.setMinimumSize(new java.awt.Dimension(74, 39));
        jPanel14.setPreferredSize(new java.awt.Dimension(334, 432));
        jPanel14.setLayout(new java.awt.GridBagLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("of");
        jLabel10.setMaximumSize(new java.awt.Dimension(14, 17));
        jLabel10.setMinimumSize(new java.awt.Dimension(14, 17));
        jLabel10.setPreferredSize(new java.awt.Dimension(14, 17));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel14.add(jLabel10, gridBagConstraints);

        jFormattedTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.################"))));
        jFormattedTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFormattedTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PercentageCalculatorGUI.this.focusLost(evt);
            }
        });
        jFormattedTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PercentageCalculatorGUI.this.keyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 34);
        jPanel14.add(jFormattedTextField2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanelPercentage.add(jPanel14, gridBagConstraints);

        jPanel15.setMinimumSize(new java.awt.Dimension(74, 39));
        jPanel15.setPreferredSize(new java.awt.Dimension(334, 432));
        jPanel15.setLayout(new java.awt.GridBagLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("is");
        jLabel11.setMaximumSize(new java.awt.Dimension(14, 17));
        jLabel11.setMinimumSize(new java.awt.Dimension(14, 17));
        jLabel11.setPreferredSize(new java.awt.Dimension(14, 17));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel15.add(jLabel11, gridBagConstraints);

        jFormattedTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.################"))));
        jFormattedTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 34);
        jPanel15.add(jFormattedTextField3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanelPercentage.add(jPanel15, gridBagConstraints);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        jPanelPercentage.add(jPanel16, gridBagConstraints);

        jPanel1.add(jPanelPercentage, "card3");

        jPanelPercentageIncreaseDecrease.setPreferredSize(new java.awt.Dimension(361, 395));
        jPanelPercentageIncreaseDecrease.setLayout(new java.awt.GridBagLayout());

        jPanel17.setBackground(new java.awt.Color(34, 40, 44));
        jPanel17.setPreferredSize(new java.awt.Dimension(361, 30));
        jPanel17.setLayout(new java.awt.GridBagLayout());

        jButtonHamburgerMenu1.setBackground(new java.awt.Color(34, 40, 44));
        jButtonHamburgerMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hamburgerMenuIcon.png"))); // NOI18N
        jButtonHamburgerMenu1.setBorder(null);
        jButtonHamburgerMenu1.setFocusPainted(false);
        jButtonHamburgerMenu1.setPreferredSize(new java.awt.Dimension(40, 30));
        jButtonHamburgerMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hamburgerMenuClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel17.add(jButtonHamburgerMenu1, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Percentage increase/decrease");
        jLabel12.setPreferredSize(new java.awt.Dimension(361, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 0.5;
        jPanel17.add(jLabel12, gridBagConstraints);

        jButtonRefresh1.setBackground(new java.awt.Color(34, 40, 44));
        jButtonRefresh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refreshIcon.png"))); // NOI18N
        jButtonRefresh1.setBorder(null);
        jButtonRefresh1.setPreferredSize(new java.awt.Dimension(40, 30));
        jButtonRefresh1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshButtonClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel17.add(jButtonRefresh1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        jPanelPercentageIncreaseDecrease.add(jPanel17, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("What is the percentage increase/decrease");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 10, 0);
        jPanel2.add(jLabel13, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        jPanelPercentageIncreaseDecrease.add(jPanel2, gridBagConstraints);

        jPanel11.setLayout(new java.awt.GridBagLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("from");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        jPanel11.add(jLabel14, gridBagConstraints);

        jFormattedTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.################"))));
        jFormattedTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFormattedTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFormattedTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PercentageCalculatorGUI.this.focusLost(evt);
            }
        });
        jFormattedTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PercentageCalculatorGUI.this.keyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 34);
        jPanel11.add(jFormattedTextField4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanelPercentageIncreaseDecrease.add(jPanel11, gridBagConstraints);

        jPanel18.setLayout(new java.awt.GridBagLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("to");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        jPanel18.add(jLabel15, gridBagConstraints);

        jFormattedTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jFormattedTextField5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.################"))));
        jFormattedTextField5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFormattedTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFormattedTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PercentageCalculatorGUI.this.focusLost(evt);
            }
        });
        jFormattedTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PercentageCalculatorGUI.this.keyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 23, 0, 34);
        jPanel18.add(jFormattedTextField5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanelPercentageIncreaseDecrease.add(jPanel18, gridBagConstraints);

        jPanel19.setLayout(new java.awt.GridBagLayout());

        jFormattedTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jFormattedTextField6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.################"))));
        jFormattedTextField6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFormattedTextField6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 58, 0, 0);
        jPanel19.add(jFormattedTextField6, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 17);
        jPanel19.add(jLabel16, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanelPercentageIncreaseDecrease.add(jPanel19, gridBagConstraints);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        jPanelPercentageIncreaseDecrease.add(jPanel20, gridBagConstraints);

        jPanel1.add(jPanelPercentageIncreaseDecrease, "card4");

        jPanel50Is1PercentOfWhatNumber.setLayout(new java.awt.GridBagLayout());

        jPanel22.setBackground(new java.awt.Color(34, 40, 44));
        jPanel22.setPreferredSize(new java.awt.Dimension(361, 30));
        jPanel22.setLayout(new java.awt.GridBagLayout());

        jButtonHamburgerMenu2.setBackground(new java.awt.Color(34, 40, 44));
        jButtonHamburgerMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hamburgerMenuIcon.png"))); // NOI18N
        jButtonHamburgerMenu2.setBorder(null);
        jButtonHamburgerMenu2.setFocusPainted(false);
        jButtonHamburgerMenu2.setPreferredSize(new java.awt.Dimension(40, 30));
        jButtonHamburgerMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hamburgerMenuClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel22.add(jButtonHamburgerMenu2, gridBagConstraints);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("50 is 1% of what number?");
        jLabel19.setPreferredSize(new java.awt.Dimension(361, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 0.5;
        jPanel22.add(jLabel19, gridBagConstraints);

        jButtonRefresh2.setBackground(new java.awt.Color(34, 40, 44));
        jButtonRefresh2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refreshIcon.png"))); // NOI18N
        jButtonRefresh2.setBorder(null);
        jButtonRefresh2.setPreferredSize(new java.awt.Dimension(40, 30));
        jButtonRefresh2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshButtonClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel22.add(jButtonRefresh2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        jPanel50Is1PercentOfWhatNumber.add(jPanel22, gridBagConstraints);

        jPanel27.setLayout(new java.awt.GridBagLayout());

        jFormattedTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jFormattedTextField7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.################"))));
        jFormattedTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFormattedTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PercentageCalculatorGUI.this.focusLost(evt);
            }
        });
        jFormattedTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PercentageCalculatorGUI.this.keyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 38, 0, 0);
        jPanel27.add(jFormattedTextField7, gridBagConstraints);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("is");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 24);
        jPanel27.add(jLabel22, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        jPanel50Is1PercentOfWhatNumber.add(jPanel27, gridBagConstraints);

        jPanel28.setLayout(new java.awt.GridBagLayout());

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("of");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 19, 0, 5);
        jPanel28.add(jLabel23, gridBagConstraints);

        jFormattedTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jFormattedTextField9.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.################"))));
        jFormattedTextField9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 39);
        jPanel28.add(jFormattedTextField9, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel50Is1PercentOfWhatNumber.add(jPanel28, gridBagConstraints);

        jPanel29.setLayout(new java.awt.GridBagLayout());

        jFormattedTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jFormattedTextField8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.################"))));
        jFormattedTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFormattedTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PercentageCalculatorGUI.this.focusLost(evt);
            }
        });
        jFormattedTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PercentageCalculatorGUI.this.keyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 38, 0, 0);
        jPanel29.add(jFormattedTextField8, gridBagConstraints);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 17);
        jPanel29.add(jLabel24, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel50Is1PercentOfWhatNumber.add(jPanel29, gridBagConstraints);

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        jPanel50Is1PercentOfWhatNumber.add(jPanel30, gridBagConstraints);

        jPanel1.add(jPanel50Is1PercentOfWhatNumber, "card5");

        jPanelWhatPercentOf.setLayout(new java.awt.GridBagLayout());

        jPanel23.setBackground(new java.awt.Color(34, 40, 44));
        jPanel23.setPreferredSize(new java.awt.Dimension(361, 30));
        jPanel23.setLayout(new java.awt.GridBagLayout());

        jButtonHamburgerMenu3.setBackground(new java.awt.Color(34, 40, 44));
        jButtonHamburgerMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hamburgerMenuIcon.png"))); // NOI18N
        jButtonHamburgerMenu3.setBorder(null);
        jButtonHamburgerMenu3.setFocusPainted(false);
        jButtonHamburgerMenu3.setPreferredSize(new java.awt.Dimension(40, 30));
        jButtonHamburgerMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hamburgerMenuClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel23.add(jButtonHamburgerMenu3, gridBagConstraints);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Percentage (What % of)");
        jLabel20.setPreferredSize(new java.awt.Dimension(361, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 0.5;
        jPanel23.add(jLabel20, gridBagConstraints);

        jButtonRefresh3.setBackground(new java.awt.Color(34, 40, 44));
        jButtonRefresh3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refreshIcon.png"))); // NOI18N
        jButtonRefresh3.setBorder(null);
        jButtonRefresh3.setPreferredSize(new java.awt.Dimension(40, 30));
        jButtonRefresh3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshButtonClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel23.add(jButtonRefresh3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        jPanelWhatPercentOf.add(jPanel23, gridBagConstraints);

        jPanel21.setLayout(new java.awt.GridBagLayout());

        jFormattedTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jFormattedTextField10.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.################"))));
        jFormattedTextField10.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFormattedTextField10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFormattedTextField10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PercentageCalculatorGUI.this.focusLost(evt);
            }
        });
        jFormattedTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PercentageCalculatorGUI.this.keyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 40, 0, 40);
        jPanel21.add(jFormattedTextField10, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        jPanelWhatPercentOf.add(jPanel21, gridBagConstraints);

        jPanel24.setLayout(new java.awt.GridBagLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("is what percent of");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        jPanel24.add(jLabel17, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 40, 0, 40);
        jPanelWhatPercentOf.add(jPanel24, gridBagConstraints);

        jPanel25.setLayout(new java.awt.GridBagLayout());

        jFormattedTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jFormattedTextField11.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.################"))));
        jFormattedTextField11.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFormattedTextField11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFormattedTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PercentageCalculatorGUI.this.focusLost(evt);
            }
        });
        jFormattedTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PercentageCalculatorGUI.this.keyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 40);
        jPanel25.add(jFormattedTextField11, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanelWhatPercentOf.add(jPanel25, gridBagConstraints);

        jPanel26.setLayout(new java.awt.GridBagLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Answer:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        jPanel26.add(jLabel18, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 40, 0, 40);
        jPanelWhatPercentOf.add(jPanel26, gridBagConstraints);

        jPanel31.setLayout(new java.awt.GridBagLayout());

        jFormattedTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jFormattedTextField12.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.################"))));
        jFormattedTextField12.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFormattedTextField12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 40);
        jPanel31.add(jFormattedTextField12, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanelWhatPercentOf.add(jPanel31, gridBagConstraints);

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        jPanelWhatPercentOf.add(jPanel32, gridBagConstraints);

        jPanel1.add(jPanelWhatPercentOf, "card6");

        jPanelFractionToPercent.setLayout(new java.awt.GridBagLayout());

        jPanel33.setBackground(new java.awt.Color(34, 40, 44));
        jPanel33.setPreferredSize(new java.awt.Dimension(361, 30));
        jPanel33.setLayout(new java.awt.GridBagLayout());

        jButtonHamburgerMenu4.setBackground(new java.awt.Color(34, 40, 44));
        jButtonHamburgerMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hamburgerMenuIcon.png"))); // NOI18N
        jButtonHamburgerMenu4.setBorder(null);
        jButtonHamburgerMenu4.setFocusPainted(false);
        jButtonHamburgerMenu4.setPreferredSize(new java.awt.Dimension(40, 30));
        jButtonHamburgerMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hamburgerMenuClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel33.add(jButtonHamburgerMenu4, gridBagConstraints);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Fraction to Percent");
        jLabel21.setPreferredSize(new java.awt.Dimension(361, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 0.5;
        jPanel33.add(jLabel21, gridBagConstraints);

        jButtonRefresh4.setBackground(new java.awt.Color(34, 40, 44));
        jButtonRefresh4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refreshIcon.png"))); // NOI18N
        jButtonRefresh4.setBorder(null);
        jButtonRefresh4.setPreferredSize(new java.awt.Dimension(40, 30));
        jButtonRefresh4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshButtonClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel33.add(jButtonRefresh4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        jPanelFractionToPercent.add(jPanel33, gridBagConstraints);

        jPanel34.setLayout(new java.awt.GridBagLayout());

        jFormattedTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFormattedTextField13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PercentageCalculatorGUI.this.focusLost(evt);
            }
        });
        jFormattedTextField13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PercentageCalculatorGUI.this.keyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 40);
        jPanel34.add(jFormattedTextField13, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        jPanelFractionToPercent.add(jPanel34, gridBagConstraints);

        jPanel35.setBackground(new java.awt.Color(0, 0, 0));
        jPanel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 0, 40);
        jPanelFractionToPercent.add(jPanel35, gridBagConstraints);

        jPanel36.setLayout(new java.awt.GridBagLayout());

        jFormattedTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFormattedTextField14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PercentageCalculatorGUI.this.focusLost(evt);
            }
        });
        jFormattedTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PercentageCalculatorGUI.this.keyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 40);
        jPanel36.add(jFormattedTextField14, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanelFractionToPercent.add(jPanel36, gridBagConstraints);

        jPanel37.setLayout(new java.awt.GridBagLayout());

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Answer:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 162, 2, 163);
        jPanel37.add(jLabel25, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanelFractionToPercent.add(jPanel37, gridBagConstraints);

        jPanel38.setLayout(new java.awt.GridBagLayout());

        jFormattedTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 40);
        jPanel38.add(jFormattedTextField15, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanelFractionToPercent.add(jPanel38, gridBagConstraints);

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        jPanelFractionToPercent.add(jPanel39, gridBagConstraints);

        jPanel40.setLayout(new java.awt.GridBagLayout());

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Convert a fraction to percent");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel40.add(jLabel26, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 40, 0, 40);
        jPanelFractionToPercent.add(jPanel40, gridBagConstraints);

        jPanel1.add(jPanelFractionToPercent, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseEntered
        
        // Change the backgound color of one of the Jpanels on mouse hover.
        JPanel thePanel = (JPanel) evt.getSource();
        thePanel.setBackground(new Color(54, 81, 207));
        
    }//GEN-LAST:event_MouseEntered

    private void MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseExited
        
        // Revert the backgound color of one of the Jpanels back to default after mouse hover. 44,52,58
        JPanel thePanel = (JPanel) evt.getSource();
        thePanel.setBackground(new Color(44,52,58));
    }//GEN-LAST:event_MouseExited

    private void mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClicked
        
            
            //This method handles the mouseClicked event for the main panels.
            //If you click on one of the panels, it will set the visibility of the layout that is associated with that panel to true.
    
            
            
            jPanelPercentage.setVisible(false);
            jPanelMain.setVisible(false);
            jPanelPercentageIncreaseDecrease.setVisible(false);
            jPanel50Is1PercentOfWhatNumber.setVisible(false);
            jPanelWhatPercentOf.setVisible(false);
            jPanelFractionToPercent.setVisible(false);

            
            int vertexCount = 5;
            ArrayList<ArrayList<JPanel>> graph = new ArrayList<>(vertexCount);
            
            //We'll initialize each element of ArrayList with another ArrayList
            for(int i=0; i < vertexCount; i++) {
                graph.add(new ArrayList());
            }
            
            graph.get(0).add(jPanel5);
            graph.get(0).add(jPanelPercentage);
            graph.get(1).add(jPanel6);
            graph.get(1).add(jPanelPercentageIncreaseDecrease);
            graph.get(2).add(jPanel7);
            graph.get(2).add(jPanel50Is1PercentOfWhatNumber);
            graph.get(3).add(jPanel8);
            graph.get(3).add(jPanelWhatPercentOf);
            graph.get(4).add(jPanel9);
            graph.get(4).add(jPanelFractionToPercent);
            
            
            
            vertexCount = graph.size();
            
            for (int i = 0; i < vertexCount; i++){

                if(graph.get(i).get(0) == evt.getSource()){
                
                    graph.get(i).get(1).setVisible(true);
                    break;
                }
            }
    }//GEN-LAST:event_mouseClicked

    private void hamburgerMenuClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hamburgerMenuClicked
        
            jPanelPercentage.setVisible(false);
            jPanelMain.setVisible(true);
            jPanelPercentageIncreaseDecrease.setVisible(false);
            jPanel50Is1PercentOfWhatNumber.setVisible(false);
            jPanelWhatPercentOf.setVisible(false);
            jPanelFractionToPercent.setVisible(false);
    }//GEN-LAST:event_hamburgerMenuClicked

    private void refreshButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshButtonClicked
        
            jFormattedTextField1.setValue(null);
            jFormattedTextField2.setValue(null);
            jFormattedTextField3.setValue(null);
            jFormattedTextField4.setValue(null);
            jFormattedTextField5.setValue(null);
            jFormattedTextField6.setValue(null);
            jFormattedTextField7.setValue(null);
            jFormattedTextField8.setValue(null);
            jFormattedTextField9.setValue(null);
            jFormattedTextField10.setValue(null);
            jFormattedTextField11.setValue(null);
            jFormattedTextField12.setValue(null);
            jFormattedTextField13.setValue(null);
            jFormattedTextField14.setValue(null);
            jFormattedTextField15.setValue(null);
    }//GEN-LAST:event_refreshButtonClicked

    private void focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusLost
        
		
		
        //This method handles the focusLost event for the jFormattedTextFields.
        //focusLost event occurs when you click on another TextField or when the text cursor leaves the current TextField.
        
        /*
        NOTE: Each jFormattedTextField works in tandem with another 2 jFormattedTextFields.
        If a jFormattedTextField is identified as the source of the event, then we would also need to identify the other 2 jFormattedTextFields that works in tandem with the event source.
        only then can we start processing what happens to the jFormattedTextFields.
        */
        
        
        //We will store all the jFormattedTextFields in a multidimensional ArrayList for processing.
        int vertexCount = 5;
        ArrayList<ArrayList<JFormattedTextField>> jFormattedTextFields = new ArrayList<>(vertexCount);
        
        //We'll initialize each element of ArrayList with another ArrayList
        for(int i=0; i < vertexCount; i++) {
                jFormattedTextFields.add(new ArrayList());
        }
        
        //We add all of the jFormattedTextFields to the multidimensional ArrayList.
        jFormattedTextFields.get(0).add(jFormattedTextField1);
        jFormattedTextFields.get(0).add(jFormattedTextField2);
        jFormattedTextFields.get(0).add(jFormattedTextField3);
        jFormattedTextFields.get(1).add(jFormattedTextField4);
        jFormattedTextFields.get(1).add(jFormattedTextField5);
        jFormattedTextFields.get(1).add(jFormattedTextField6);
        jFormattedTextFields.get(2).add(jFormattedTextField7);
        jFormattedTextFields.get(2).add(jFormattedTextField8);
        jFormattedTextFields.get(2).add(jFormattedTextField9);
        jFormattedTextFields.get(3).add(jFormattedTextField10);
        jFormattedTextFields.get(3).add(jFormattedTextField11);
        jFormattedTextFields.get(3).add(jFormattedTextField12);
        jFormattedTextFields.get(4).add(jFormattedTextField13);
        jFormattedTextFields.get(4).add(jFormattedTextField14);
        jFormattedTextFields.get(4).add(jFormattedTextField15);
        
        
        //Loop through the entire multidimensional ArrayList to search for the source of the focusLost event.
        for (int i = 0; i < vertexCount; i++){
        
            int arrayListElementSize = jFormattedTextFields.get(i).size();
            
            for (int j = 0; j < arrayListElementSize; j++){
            
                //If the event source is identified.
                if(jFormattedTextFields.get(i).get(j) == evt.getSource()){
                
                    //We retrieve the contents of the source and the other jFormattedTextField associated with it for validation.
                    String content;
                    String content2;
                    content = jFormattedTextFields.get(i).get(0).getText().trim();
                    content2 = jFormattedTextFields.get(i).get(1).getText().trim();
                    
                    
                    //Validate the inputs of the source and its associated jFormattedTextField.
                    if(validateJFormatterTextFieldValue(content)){
                    
                        jFormattedTextFields.get(i).get(0).setText(content);
                    }
                    else{
                        
                        //If the validation fails, delete the inputs, including the contents of the result textField.
                        jFormattedTextFields.get(i).get(0).setValue(null);
                        jFormattedTextFields.get(i).get(2).setValue(null);
                    }
                    
                    
                    if(validateJFormatterTextFieldValue(content2)){
                    
                        jFormattedTextFields.get(i).get(1).setText(content2);
                    }
                    else{
                    
                        //If the validation fails, delete the inputs, including the contents of the result textField.
                        jFormattedTextFields.get(i).get(1).setValue(null);
                        jFormattedTextFields.get(i).get(2).setValue(null);
                    }
                    
                    
                    break;
                }
            }
			
			
        }
    }//GEN-LAST:event_focusLost

    private void keyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyReleased
        
		
		//This method handles the keyReleased event for the jFormattedTextFields.
        //keyReleased event occurs when you release a key on your keyboard after pressing or clicking on it.
        
        /*
        NOTE: Each jFormattedTextField works in tandem with another 2 jFormattedTextFields.
        If a jFormattedTextField is identified as the source of the event, then we would also need to identify the other 2 jFormattedTextFields that works in tandem with the event source.
        only then can we start processing what happens to the jFormattedTextFields.
        */
        
        
        //We will store all the jFormattedTextFields in a multidimensional ArrayList for processing.
        int vertexCount = 5;
        ArrayList<ArrayList<JFormattedTextField>> jFormattedTextFields = new ArrayList<>(vertexCount);
        
        
        //We'll initialize each element of ArrayList with another ArrayList
        for(int i=0; i < vertexCount; i++) {
                jFormattedTextFields.add(new ArrayList());
        }
        
        
        //We add all of the jFormattedTextFields to the multidimensional ArrayList.
        jFormattedTextFields.get(0).add(jFormattedTextField1);
        jFormattedTextFields.get(0).add(jFormattedTextField2);
        jFormattedTextFields.get(0).add(jFormattedTextField3);
        jFormattedTextFields.get(1).add(jFormattedTextField4);
        jFormattedTextFields.get(1).add(jFormattedTextField5);
        jFormattedTextFields.get(1).add(jFormattedTextField6);
        jFormattedTextFields.get(2).add(jFormattedTextField7);
        jFormattedTextFields.get(2).add(jFormattedTextField8);
        jFormattedTextFields.get(2).add(jFormattedTextField9);
        jFormattedTextFields.get(3).add(jFormattedTextField10);
        jFormattedTextFields.get(3).add(jFormattedTextField11);
        jFormattedTextFields.get(3).add(jFormattedTextField12);
        jFormattedTextFields.get(4).add(jFormattedTextField13);
        jFormattedTextFields.get(4).add(jFormattedTextField14);
        jFormattedTextFields.get(4).add(jFormattedTextField15);
        
        
        //Loop through the entire multidimensional ArrayList to search for the source of the focusLost event.
        for (int i = 0; i < vertexCount; i++){
        
            int arrayListElementSize = jFormattedTextFields.get(i).size();
            
            //If the event source is identified.
            for (int j = 0; j < arrayListElementSize; j++){
            
                    //We retrieve the contents of the source and the other jFormattedTextField associated with it for validation.
                    String content;
                    String content2;
                    content = jFormattedTextFields.get(i).get(0).getText().trim();
                    content2 = jFormattedTextFields.get(i).get(1).getText().trim();
                    
                    
                    //Validate the inputs of the source and its associated jFormattedTextField.
                    if(validateJFormatterTextFieldValue(content) && validateJFormatterTextFieldValue(content2)){
                    
                        System.out.println("True");
                        //We start our calculation here by calling the calculate() method and passing in all the necessary arguments.
                        calculate(i, jFormattedTextFields.get(i).get(0), jFormattedTextFields.get(i).get(1), jFormattedTextFields.get(i).get(2));
                        break;
                    }
                    else{
                    
                        //If the validation fails, we set the value of the result textField to null.
                        System.out.println("False");
                        jFormattedTextFields.get(i).get(2).setValue(null);
                        break;
                    
                    }
                    
            }
        }
		
    }//GEN-LAST:event_keyReleased

    
    

    
    private boolean validateJFormatterTextFieldValue(String content){
        
        //This method validates the inputs from the jFormatterTextFields.
        //It uses REGEX to validate the inputs.
        
         /*The REGEX checks for the following number formats:
            
          00000.00000
          .12345
          0.12345
          00000.12345
          -12345.12345
          -12,345.12345
          123,123,123.12345
          12345.12345
          1000
          1,000
          -50
          -50.12345
        
        */     
        if(Pattern.matches("([0]+)(\\.[0]+)*|(\\.\\d+)|([0]+)(\\.\\d+)*|\\-[1-9]+(\\.\\d+)*|\\-[1-9]{1,3}(\\,\\d{3})+(\\.\\d+)?", content)){
            
            return true;
        }
        else if(Pattern.matches("(\\d{1,3})(\\,\\d{3})*(\\.\\d+)?|\\d+(\\.\\d+)|\\d+|\\-[0]*[1-9]+[0]*(\\.\\d+)*", content)){
            
            return true;
        }
        
        return false;
        
    }



    private void calculate(int index, JFormattedTextField a, JFormattedTextField b, JFormattedTextField c){
    
       
        //This method is called after we have finished the input validations and we are ready to calculate.
        //For the calculation, we use the PercentageCalculator class.
        //It uses the BigDecimal type to store the inputs and to format the result.
        //BigDecimal type is capable of setting how many decimal value the result will have.
        //BigDecimal can also strip trailing zeroes.
        //BigDecimal can also use different rounding methods.
        //We use the switch statement to determine what method of the PercentageCalculator class to use
        //and what type of calculation to perform.
        //The switch statement relies on the index of the jFormattedTextFields ArrayList to determine the appropriate method to call.
        //This index is associated with the keyReleased event source.
        //There is no need for the user to click a "calculate" button
        //since the input validation and calculation is done while the user is typing.
        
        PercentageCalculator pc = new PercentageCalculator();
        
        BigDecimal value = new BigDecimal(a.getText().trim().replace(",", ""));
        double d = value.doubleValue();
                    
        BigDecimal value2 = new BigDecimal(b.getText().trim().replace(",", ""));
        double d2 = value2.doubleValue();
        
        double d3 = 0;
        
        try{
            
            switch (index) {
              case 0:
                d3 = pc.APercentOfB(d, d2);
                break;
                
              case 1:
                d3 = pc.percentageDecreaseIncrease(d, d2);
                break;
                
              case 2:
                d3 = pc.FiftyIsOnePercentOfWhatNumber(d, d2);
                break;
                
              case 3:
                d3 = pc.whatPercentOf(d, d2);
                break;
                
              case 4:
                d3 = pc.whatPercentOf(d, d2);
                break;
            }
            
            BigDecimal bd = new BigDecimal(d3);
            bd = bd.setScale(12, RoundingMode.HALF_UP);
            bd = bd.stripTrailingZeros();
            c.setText(bd.toPlainString());
            
        }catch(HandledException e){
        
            c.setText(e.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHamburgerMenu;
    private javax.swing.JButton jButtonHamburgerMenu1;
    private javax.swing.JButton jButtonHamburgerMenu2;
    private javax.swing.JButton jButtonHamburgerMenu3;
    private javax.swing.JButton jButtonHamburgerMenu4;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonRefresh1;
    private javax.swing.JButton jButtonRefresh2;
    private javax.swing.JButton jButtonRefresh3;
    private javax.swing.JButton jButtonRefresh4;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField10;
    private javax.swing.JFormattedTextField jFormattedTextField11;
    private javax.swing.JFormattedTextField jFormattedTextField12;
    private javax.swing.JFormattedTextField jFormattedTextField13;
    private javax.swing.JFormattedTextField jFormattedTextField14;
    private javax.swing.JFormattedTextField jFormattedTextField15;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JFormattedTextField jFormattedTextField9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50Is1PercentOfWhatNumber;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelFractionToPercent;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelPercentage;
    private javax.swing.JPanel jPanelPercentageIncreaseDecrease;
    private javax.swing.JPanel jPanelWhatPercentOf;
    // End of variables declaration//GEN-END:variables
}
